"""
ML Service — loads the trained RandomForest model and performs predictions.
The model expects 15 features in this exact order:
  HighBP, HighChol, CholCheck, BMI, Smoker, Stroke, Diabetes,
  PhysActivity, Fruits, Veggies, HvyAlcoholConsump, GenHlth,
  DiffWalk, Sex, Age
"""

import os
import joblib
import numpy as np
from models.prediction import PredictionInput, PredictionOutput

# Path to the trained model file (generated by model/train.py)
MODEL_PATH = os.path.join(os.path.dirname(__file__), "..", "..", "model", "heart_disease_model.pkl")

_model = None


def load_model():
    """Load the model into memory (called once at startup)."""
    global _model
    if os.path.exists(MODEL_PATH):
        _model = joblib.load(MODEL_PATH)
        print(f"✅ ML model loaded from {MODEL_PATH}")
    else:
        print(f"⚠️  Model file not found at {MODEL_PATH}. Run train_model.py first.")


def get_model():
    """Return the loaded model instance."""
    return _model


def prepare_features(data: PredictionInput) -> list:
    """Convert PredictionInput to the feature vector expected by the model."""
    return [
        data.high_bp,
        data.high_cholesterol,
        data.cholesterol_check,
        data.bmi,
        data.smoker,
        data.stroke,
        data.diabetes,
        data.physical_activity,
        data.fruits,
        data.veggies,
        data.heavy_alcohol,
        data.general_health,
        data.difficulty_walking,
        data.sex,
        data.age,
    ]


PREDICTION_THRESHOLD = 0.25  # Lower than 0.5 to improve recall for disease cases


def classify_risk(probability: float) -> str:
    """
    Map probability to risk category.
    Thresholds tuned to the class-balanced RandomForest model
    (probabilities tend to be lower than a vanilla model).
    """
    if probability < 0.15:
        return "Low"
    elif probability < PREDICTION_THRESHOLD:  # 0.25
        return "Medium"
    else:
        return "High"


def predict(data: PredictionInput) -> PredictionOutput:
    """Run prediction and return structured output."""
    model = get_model()
    if model is None:
        raise RuntimeError("ML model is not loaded. Please train and place the .pkl file.")

    features = prepare_features(data)
    feature_array = np.array([features])

    # predict_proba returns [[prob_class_0, prob_class_1]]
    probabilities = model.predict_proba(feature_array)
    prob_disease = float(probabilities[0][1])
    prob_no_disease = float(probabilities[0][0])

    risk_category = classify_risk(prob_disease)

    # Confidence = how certain the model is about its top prediction
    confidence = max(prob_disease, prob_no_disease)

    return PredictionOutput(
        probability=round(prob_disease, 4),
        risk_percentage=round(prob_disease * 100, 2),
        risk_category=risk_category,
        confidence_score=round(confidence, 4),
        input_summary=data.model_dump(),
    )
